env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1"

window:
  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 10
    y: 10

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack NF
    style: Regular

  bold:
    family: Hack NF
    style: Bold

  italic:
    family: Hack NF
    style: Italic

  bold_italic:
    family: Hack NF
    style: Bold Italic

  size: 9.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

background_opacity: 0.9

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

dynamic_title: true
# Oxide colors
colors:
  primary:
    background: '#212121'
    foreground: '#c0c5ce'
    bright_foreground: '#f3f4f5'

  cursor:
    text: '#212121'
    cursor: '#c0c5ce'

  normal:
    black:   '#212121'
    red:     '#e57373'
    green:   '#a6bc69'
    yellow:  '#fac863'
    blue:    '#6699cc'
    magenta: '#c594c5'
    cyan:    '#5fb3b3'
    white:   '#c0c5ce'

  bright:
    black:   '#5c5c5c'
    red:     '#e57373'
    green:   '#a6bc69'
    yellow:  '#fac863'
    blue:    '#6699cc'
    magenta: '#c594c5'
    cyan:    '#5fb3b3'
    white:   '#f3f4f5'

  indexed_colors: []


