#!/bin/bash

# ASDF
export ASDF_CONCURRENCY=$(nproc)
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash


# Rust
if [ -f $HOME/.cargo/env ]; then
	source $HOME/.cargo/env
fi

# Go
export PATH=/usr/local/go/bin:$PATH

# Zig
if [ -f /usr/local/zig/current/zig ]; then
	export PATH=/usr/local/zig/current:$PATH
fi

# Home Bin
export PATH=$HOME/bin:$HOME/.local/bin:$HOME/go/bin:$PATH
# Add Seamonkey ;)
export PATH=/opt/seamonkey/:$PATH

# Historical Arrows:
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Neovim as Editor
export EDITOR=$(which nvim)

# Prettier LS
alias ls='lsd'
 
# Starship
# sudo snap install starship
eval "$(starship init bash)"

# direnv
eval "$(asdf exec direnv hook bash)"

# A shortcut for asdf managed direnv.
direnv() { asdf exec direnv "$@"; }

# Tmux
alias tmux='tmux -2'

# LSD
alias ls='lsd'

alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias llah='ls -alh'
alias lt='ls --tree'

